### ISSUE TITLE
Track app errors

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/android-app#17]
We probably want to track errors (caught and uncaught)
like services dying, networking / serialisation failures, and app crashes

@kimar are you already using something like these?
https://rollbar.com/
http://www.crittercism.com/
https://try.crashlytics.com/

**Comment by kimar** [comment]
Hi, I've been using Fabric.io on iOS but I wouldn't mind if you said that another service is more suitable.
I'd leave this up to you.
You probably wouldn't want to check in the App Key / ID for the service, right?

**Comment by francisdb** [comment]
No preference, fabric.io looks fine to me.

**Comment by francisdb** [comment]
@kimar can that fabric account be shared?

**Comment by kimar** [comment]
Yeah I'd just need to securely send you the credentials somehow.

**Comment by francisdb** [comment]
But maybe you can have multiple members in your project?

**Comment by kimar** [comment]
:facepunch: sure we can! shoot me your mail address at marcus@kida.io

**Comment by francisdb** [comment]
After a while the app stops reporting fences, I guess this is related to some error in the service. Fabric should help us to track this.

**Comment by kimar** [comment]
Cool, thx for looking into this. Just out of experience also take things like backgrounding into your mind. Tricked me more than once on iOS. Don't know how this works in general on Android though.

**Comment by francisdb** [comment]
Not even sure what that term implicates... Anyway, we only react on fences which google tells us about

**Comment by francisdb** [comment]
I guess we can also close this one
