### ISSUE TITLE
Redesign ......

### ISSUE THREAD

**Issue by chrissd23** [LocativeHQ/android-app#23]
Hi, 

I think about a new design. I think that we could use more material design aspects.

What do you think @kimar @francisdb ...?

**Comment by kimar** [comment]
Yeah I think @tbasse already worked on a redesign (for iOS).
You could do some material ui stuff but I'd rather not change too much and maybe align it to the potential new design. We'll look into this soon-ish.

**Comment by francisdb** [comment]
@ChrisDolge agree, and for @kimar I don't think the android app should copy the iOS app for design. It should only try to have the same functionality. But I don't have a view on this as i have no iOS devices at home.

**Comment by kimar** [comment]
@francisdb totally agree here. I didn't mean to do a 1:1 design but rather realize it using well-known Android design patterns while still keeping the Locative CI/CD

**Comment by kimar** [comment]
@francisdb @chrisdolge I'm sure both of you are better Android devs (and also users) than I, so I'd rather leave this up to you than fiddle around there with my iOS bias

**Comment by ChrisDolge** [comment]
@kimar  I agree with you to keep the Locative CD. 

Do you know when @tbasse finished his redesign work? It would be good to see some screenshots after that. :) 

Cheers ;)

**Comment by kimar** [comment]
Probably needs some more work, just do what you think suits best for now. We're then trying to unclutter the UI later on. Right now I'm also thinking completely rewriting the iOS app as there's lots of stuff that's :hankey:

**Comment by ChrisDolge** [comment]
Ok :smile:

**Comment by francisdb** [comment]
I'm far from a android UX/UI expert, have not been following the space too much

**Comment by tbasse** [comment]
I had worked on some new layouts a good while ago but by now they are pretty outdated again. I'll bring them up to date and post screens then.

**Comment by kimar** [comment]
@tbasse :clap: nice

**Comment by ChrisDolge** [comment]
Great @tbasse :+1:

**Comment by francisdb** [comment]
see #50 for the settings activity

**Comment by francisdb** [comment]
I guess it would be better to have more actionable tickets where it's easier to discuss a specific view

**Comment by francisdb** [comment]
I suggest we close this for now. @tbasse in case you come up with something feel free to reopen
