### ISSUE TITLE
Rebranding to 'Locative'

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/android-app#24]
Geofancy is soon being called Locative.
Will need to change this inside on the Android side too.

**Comment by ChrisDolge** [comment]
Ok , 

Only the app name ...?

**Comment by francisdb** [comment]
Since nothing is in the store yet I would also rename packages and app identifier

**Comment by francisdb** [comment]
@ChrisDolge will you take care of this? Just that we don't both do this.

**Comment by ChrisDolge** [comment]
Yes

I can do this. I think later on this day ;)

**Comment by kimar** [comment]
Yeah thx :+1: App name shall be. "Locative" and backend is now "https://my.locative.io", bundle ID can be "io.locative" or "io.locative.android" or whatever suits it in Android-Land :-)

**Comment by francisdb** [comment]
I suggest to unify the Not sure if this is important but would be nice if we could unify the id and the resource package

https://github.com/Geofancy/android-app/blob/master/app/build.gradle#L37

**Comment by kimar** [comment]
Sure why not, as long as we haven't published it, we can do whatever we want with it :yum:

**Comment by francisdb** [comment]
Any more work on this one?

**Comment by ChrisDolge** [comment]
I think all is done :+1:
