### ISSUE TITLE
Notification icon needed

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/android-app#31]
Currently notifications show a pale circle. We need a proper icon.

**Comment by kimar** [comment]
On iOS this automatically shows the app icon, could you post a screenshot of how this notification looks like?

**Comment by francisdb** [comment]
We could use this to generate them:
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html

Do you have the icon in svg?

**Comment by kimar** [comment]
Only got those present in the iOS app's asset folder, blue 'n black, but should be feasible to convert them I'd guess. https://github.com/LocativeHQ/ios-app/tree/master/Assets/Icons

Maybe I and @tbasse can come up with something better in the future.

**Comment by francisdb** [comment]
Well would not hurt to have vector icon + full logo in svg somewhere? Square and long versions.

**Comment by kimar** [comment]
Yeah definitely :+1: don't have anything like that though

**Comment by francisdb** [comment]
So we then wait for @tbasse to come up with the svg's?
I can take it from there

**Comment by kimar** [comment]
I'm not sure if he's available or too busy right now, but I think this can wait a bit, right? Otherwise I could see if I can find an old vector one or, in the worst case, vectorize the existing one...

**Comment by francisdb** [comment]
nah, not urgent

**Comment by francisdb** [comment]
Here you have some screensots

Notification when screen locked

![screenshot_20151203-091338](https://cloud.githubusercontent.com/assets/161305/11557228/eea926d8-99ab-11e5-9593-36c0ab8d338c.png)

Notifications when unlocked and swiped down

![screenshot_20151203-083658](https://cloud.githubusercontent.com/assets/161305/11557229/ef89f69a-99ab-11e5-8674-c3205ab2de3c.png)

**Comment by kimar** [comment]
Wow awesome, so cool to see it actually in action. Really good work @francisdb and @chrisdolge can't wait to have this submitted to the play store 🎉 thx a bunch already! @tbasse is also working hard on some new designs on iOS, we'll ping you as soon as we've got something to show. maybe we should create a design repo for this

**Comment by francisdb** [comment]
@kimar @tbasse 3 months later...
Another request for vector icon + full logo in svg somewhere?

**Comment by kimar** [comment]
@francisdb I've just vectorized the App Store logo (which is the same as the iOS App icon) and created a new repo for all the assets here: https://github.com/LocativeHQ/assets/tree/master/icons/vectorized

Hope this helps. I'd also be open for modifications to the icon and CD in general.

**Comment by francisdb** [comment]
@kimar thanks! What's CD?

**Comment by chrissd23** [comment]
@francisdb CD = corporate design

**Comment by kimar** [comment]
@francisdb did you use the icons orovides for the notifications? I'm asking because I'm checking what we might need to submit to the Play Store

**Comment by francisdb** [comment]
not yet, sorry, need some time to apply this

**Comment by kimar** [comment]
No worries, just askin', you can update this issue in case you're working on it, otherwise I might also take a look into this, if I find some time.

**Comment by francisdb** [comment]
@jasperdevrient could you also update the icon to use:
https://github.com/LocativeHQ/assets/tree/master/icons/vectorized ?

app main icon is blurry, same with notification icons

**Comment by jasperdevrient** [comment]
Ok I will fix this

**Comment by francisdb** [comment]
The geofence list also has blurry icons

**Comment by jasperdevrient** [comment]
@francisdb It used the same image, I have added more versions to handle screens with a bigger DPI.

**Comment by francisdb** [comment]
@jasperdevrient way better 👍

**Comment by francisdb** [comment]
@jasperdevrient Looks like I found some other icon issues

Lock screen (too small icons)
![lockscreen](https://cloud.githubusercontent.com/assets/161305/14910299/63c089fc-0dec-11e6-9b9e-43cdb0db35a0.png)

Notification icons (icon not visible, just shows square)
![notifiation icons](https://cloud.githubusercontent.com/assets/161305/14910302/69fb6cd8-0dec-11e6-834b-aad8db91840b.png)

Notification dropdown (shows 2 icons, small one is not needed)
![notifications-dropdown](https://cloud.githubusercontent.com/assets/161305/14910314/75ba7550-0dec-11e6-93b0-ca71604562d4.png)
