### ISSUE TITLE
Sync serverside and clientside geofences

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/android-app#4]
Currently creating a serverside geofence does not add it to the app (best would be some kind of push notification if the list of fences changes)

Also in-app geofences are not stored online

**Comment by kimar** [comment]
In the iOS App you have to do this manually. I've been working on a sync mechanism once but it's pretty much stalled. Would also need some work on the server side of things, still thinking of open sourcing the cloud app too...will need some refactoring though. I'm on this topic.

**Comment by francisdb** [comment]
Will work on this next. How is the current manual sync done? Only copying serverside to app, the other way round or both? I thought about adding a sync action on the fence list view which would copy over serverside fences to the app.
Do you have something like last modified date to be able to know what version is more recent?

**Comment by francisdb** [comment]
@kimar I see I got access to the project but can not assign this ticket to me. Can you also reply to the question above?

**Comment by francisdb** [comment]
Would it not be simpler to just do auto sync? Like anything from the server overrides local info in the app.

**Comment by kimar** [comment]
Easier yes but as the iOS app existed long before there was the web service, I didn't want to mess up with user created Geofences inside the app so I had to make sure those don't get overridden.

There's this `sync` method which delviers a delta of the Geofences on the server (removed and added) but that's certainly not a enough to do a full-fledge sync (but it might be a beginning): https://github.com/Geofancy/cloud-app/blob/master/routes/api/geofences.js#L53

I can port this thing over to oAuth 2.

On the other hand I'd be fine with the fact that Android just does overwriting the local fences with the cloud fences by let's say having a "Restore from Cloud" button etc... then the user might be warned before using it and we just do a local wipe and import all from cloud. We can still improve this over time.

**Comment by francisdb** [comment]
To do a real sync we would need a last update date, that way in a 2-way sync the last version wins. And you also need to keep track of deleted fences (soft delete)

**Comment by kimar** [comment]
That’s already implemented on server side, both the deleted flag and also query with lastUpdate timestamp. 

```
https://my.geofancy.com/api/geofences/sync?lastSync={timestamp}&token={accessToken}
```

**Comment by francisdb** [comment]
hmm, is that enough for a 2-way sync?

**Comment by kimar** [comment]
The app would have to do it's own delta and send all missing Geofences, I'd rather like to put more of this stuff onto the server side, so I'd agree with you that we might need a bit more there. Also maybe we might want to use the HTTP `PATH` method?

**Comment by francisdb** [comment]
Actually, I have never coded this kind of stuff but I guess many people have solved this before. Anyway, let me just start with a server to app sync.

As I mentioned before I envision an app that is totally controlled by the server and does not even need a ui. The app could then optionally behave like a public api client for setting up the fences.

Currently all the fields in the app on server url and POST/GET are confusing and make it too geeky. Should probably be more like advanced mode for use without geofancy backend. (or a separate app)

**Comment by kimar** [comment]
I'm fine with that, sounds good to me :+1:

**Comment by francisdb** [comment]
@kimar a general geofancy gitter chat might be better than all this ticket abusing?

**Comment by kimar** [comment]
Haha yeah definitely. Will add this.

**Comment by kimar** [comment]
This is basically how it looks like on iOS.
1. Chose weather to import or add local one after clicking the **+**:

![img_9943](https://cloud.githubusercontent.com/assets/126418/11230693/160b162c-8df5-11e5-8b2d-61b3016879c5.PNG)

2. Select a Geofence and it will be imported straight away:

![img_9944](https://cloud.githubusercontent.com/assets/126418/11230695/1784e9a6-8df5-11e5-9882-d82f296c1029.PNG)

**Comment by francisdb** [comment]
@jasperdevrient think this would be something you could manage?

**Comment by jasperdevrient** [comment]
@francisdb Ok I will do this. So when the user hits the Add button he should be prompted if he wants to create a new fence or import one from the server (which would display a list available geofences). But then when the user edits or remove a fence (that is from the server) these changes have aslo to be synced to the server. So on the localstorage level a distinction should be made?

@kimar Can I use the column `Type` in the `GeofenceProvider` to determine wheater the geofence is online or locally?

**Comment by francisdb** [comment]
I guess you could just add a sync button?

**Comment by kimar** [comment]
@jasperdevrient no the `type` is meant to distinguish between `iBeacon` (or the Android equivalent) and `Geofence`. On iOS I'm not using this at all as the sync isn't implemented. You have to manually up-/download the fences. But I'd be keen to implement and test the sync. So feel free to add an attribute or propose changes to the existing model.

**Comment by jasperdevrient** [comment]
@kimar Ok for the first version I will implement it as a simple download of the fence and added it to the local database. In the next versions I will change this to support sync.

**Comment by kimar** [comment]
Awesome @jasperdevrient :+1:

**Comment by francisdb** [comment]
@kimar is there a reason to not just always do full two-way sync?

**Comment by kimar** [comment]
@francisdb right now the only reason for me is that it's not been tested yet. No unit- / integration tests also I didn't extensively test this manually. Don't want to roll this out in production and mess up the user's Geofences. I'll see that I get this implemented into iOS at some point.

**Comment by francisdb** [comment]
@jasperdevrient The import is still wrong, address is set to customId and customId is set to the real id.
Instead address should be empty and customId should be the server's geofence customId.
