### ISSUE TITLE
Missing Runtime Permissions for Android Version 6.0

### ISSUE THREAD

**Issue by chrissd23** [LocativeHQ/android-app#41]
There is no run time permission request in LocationService.java.

**Comment by kimar** [comment]
Sounds good, what do we need to do to achieve this? I don't have much experience with Android 6.x

**Comment by francisdb** [comment]
see http://developer.android.com/training/permissions/requesting.html

**Comment by chrissd23** [comment]
I can afford some time to fix this next weekend or @francisdb would you like to do this ... :) ?

**Comment by francisdb** [comment]
@chrissd23 go ahead, please assign yourself to the ticket when you start working on it

**Comment by robertbaptiste** [comment]
Fixed with #42

**Comment by francisdb** [comment]
@robertbaptiste since you are not on gitter I'm asking here. Do you also have the problem where the app after a while does not trigger fence logs any more? Could be related to restarting my phone.

**Comment by robertbaptiste** [comment]
Hi @francisdb,

I didn't notice this one but I didn't test the app a lot. I need to use more the app and I will tell you :)
