### ISSUE TITLE
Submit to the Play Store

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/android-app#44]
Once Ready. Potentially still blocked by other issues.

**Comment by francisdb** [comment]
Might be good to create a milestone for this?

**Comment by kimar** [comment]
Sure thing! 👍

**Comment by kimar** [comment]
I've set up a draft for this in my Play Store Account, I'll need to create some assets and screenshots etc. but I'm aiming to publish this in the upcoming weeks. //cc @francisdb

**Comment by francisdb** [comment]
looking forward to it 🙌

**Comment by kimar** [comment]
![screen shot 2016-07-08 at 9 17 57 am](https://cloud.githubusercontent.com/assets/126418/16672933/e63a78c0-44ec-11e6-805a-18273ec3fb84.png)

Not sure what went wrong here but they instantly suspended the app. No chance of changing anything to it right now. Will have to wait until they get back to me. Worse experience than on the App Store so far 👎

**Comment by francisdb** [comment]
Wat?
What does the mail with details say?

**Comment by kimar** [comment]
> After review, Locative, io.locative.app, has been suspended and removed from Google Play as a policy strike because it violates the impersonation policy.

I've contacted support but they'll most likely need some time to get back. I'll update this issue if I know more.

**Comment by kimar** [comment]
Problem solved, here we go: https://play.google.com/store/apps/details?id=io.locative.app

**Comment by francisdb** [comment]
Great!
