### ISSUE TITLE
Fabric / Crashlytics

### ISSUE THREAD

**Issue by chrissd23** [LocativeHQ/android-app#45]
Hi guys, 

I think we should implement fabric/crashlytics to the application. So we have good crash report and some other analytics stuff at first.

I've added this framework to our company application and it works fine for me :) 

What do you think ? @kimar @francisdb

**Comment by francisdb** [comment]
@chrissd23 there already is an account, you can ask @kimar for credentails. My local version had it set up but then I got conflicts with the recent merges so never made it.

Let me see if I can add you

see #17

**Comment by kimar** [comment]
@chrissd23 @francisdb yeah we already talked about this, there's even already a Locative org @ Fabric and the android app has already been added. Also both of you are already part of the fabric team so we basically just need to implement this.

**Comment by francisdb** [comment]
Great, @chrissd23 do you add this stuff?

**Comment by chrissd23** [comment]
@kimar @francisdb  Yes , I can add this ;)

**Comment by kimar** [comment]
Awesome @chrissd23 !

**Comment by chrissd23** [comment]
I have some problems with Travis CI.

I would like to hide the public fabric api from our repo. So I add a local property file with this key. If I build the app locally it works fine.  

If I leave the api key in android manifest file -> Travis CI build failed  :( 

So I have no perfect solution for this problem. Maybe do you have some ideas @francisdb @kimar

**Comment by chrissd23** [comment]
I found a solution. I need some test :)

**Comment by kimar** [comment]
@chrissd23 awesome :+1:, I'd like to add the key to travis as a build environment variable so we don't expose it publicly. I'll also add Crashlytics to the iOS app as soon as possible (aka. when I find some time)

**Comment by chrissd23** [comment]
Sounds great @kimar 

You need to add these two variables 

export ORG_GRADLE_PROJECT_crashlyticsdemoApikey="  "
export ORG_GRADLE_PROJECT_crashlyticsdemoApisecret ="  "

I think that's it :)

**Comment by chrissd23** [comment]
I was wondering whether we should disable crashlytics for debug build ? Because we see all the crashes in out IDE :) 

What's your opinion ? @kimar @francisdb

**Comment by kimar** [comment]
@chrissd23 great thx I'll add those, can we please make them all upper case? With underscores in between? That's the convention for env vars afaik. And yes we should totally disable this for Debug!

**Comment by chrissd23** [comment]
Done :smile:

**Comment by francisdb** [comment]
:+1 for disabling crashlytics for debug builds

**Comment by kimar** [comment]
@chrissd23 awesome thank you!
